# fly.toml app configuration file generated for chastity on 2023-06-24T22:19:37+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chastity"
primary_region = "nrt"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  CHASTER_CLIENT_ID = "test-808352"
  # CHASTER_CLIENT_SECRET = ""
  CHASTER_REDIRECT_URI = "https://chastity.fly.dev/oidc"
  SESSION_COOKIE_SECURE_OPTION = "true"
  # SESSION_SECRET = ""
